language: ruby
bundler_args: "--without development production"
rvm:
- 2.2
addons:
  postgresql: "9.3"
before_script:
- cp .env.example .env
- cp config/database.yml.example config/database.yml
- bin/rake db:create db:schema:load RAILS_ENV=test
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: amPyN3WHIef60hgcQxTPFzf4KOnX5ihfiJ7yFxEHe0mOLVYtv6qN+0Ac46hSNJg1qR3ndG8jlVuE36FMwhBaqgdi26pNHnJpv/yfEiqV+7w26M8khF1e4WURbEWun/SoZZZxOU/E/DIGKo1LLOlreH35rjkJMWJjnKD6791aWY0=
  app: helpful-production
  on:
    repo: asm-helpful/helpful-web
  run:
    - "rake db:migrate"
    - restart
    - "rake cleanup"
